version: '2'

services:
  mysql:
    build:
      context: ./services/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./services/mysql/datadir:/var/lib/mysql

  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./services/nginx/sites:/etc/nginx/conf.d
      - ./services/nginx/logs:/var/log/nginx

  tools:
    build:
      context: ./services/tools
      dockerfile: Dockerfile
    volumes_from:
      - php
    tty: true

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
