version: '2'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./services/mysql/conf:/etc/mysql/conf.d
      - ./services/mysql/datadir:/var/lib/mysql

  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html/

  nginx:
    image: nginx:1.12.1
    ports:
      - "80:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./services/nginx/sites:/etc/nginx/conf.d
      - ./services/nginx/logs:/var/log/nginx
    command: /bin/bash -c "nginx -g 'daemon off;'"

  tools:
    build:
      context: ./services/tools
      dockerfile: Dockerfile
    volumes_from:
      - php
    tty: true

  node:
    build:
      context: ./services/node
      dockerfile: Dockerfile
    volumes_from:
      - php
    tty: true

  redis:
    image: redis:3.2.10
    ports:
      - "6379:6379"
    volumes_from:
      - php
